name: ParticleHats
main: com.mediusecho.particlehats.ParticleHats
version: 4.2.16
api-version: 1.13
author: MediusEcho
softdepend: [Vault, SuperVanish, PremiumVanish, VanishNoPacket, PlayerPoints, Citizens, TokenManager]
commands:
  h:
    description: Main command for ParticleHats
    aliases: ph
    